DROP TABLE ODONTOLOGOS  IF EXISTS;

CREATE TABLE ODONTOLOGOS
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MATRICULA varchar(25) NOT NULL,
    NOMBRE VARCHAR(25) NOT NULL,
    APELLIDO VARCHAR(25) NOT NULL
);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 1,'Andrea', 'cordoba');
INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 1,'Diego', 'Torres');